name: Build & test on ubuntu

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 5.0.x
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: |
          for i in {0..60}
            do 
              dotnet test --no-restore --verbosity normal
            done
      - name: fsharpLint
        run: |
          dotnet tool install --global dotnet-fsharplint --version 0.19.2

          # path taken from https://stackoverflow.com/a/65367006/544947
          $HOME/.dotnet/tools/dotnet-fsharplint lint NOnion.sln

      # FIXME: use `continue-on-error: true` when we figure out how to have a
      #        visual warning icon (instead of green tick) on GitHubActionsCI
      - name: fantomas
        run: |
          dotnet tool install --global fantomas-tool --version 4.5.0

          # path taken from https://stackoverflow.com/a/65367006/544947
          $HOME/.dotnet/tools/fantomas --recurse .
          git diff --exit-code
